### PR TITLE
Single error and disable on influx error

### LINKED ISSUE #126: demo broken
I've just pulled master 

```js
ReferenceError: data is not defined
    at Seneca.<anonymous> (/Users/matteo/Repositories/vidi-dashboard/node_modules/vidi-toolbag-influx/toolbag-influx.js:124:27)
    at Seneca.delegate.prior (/Users/matteo/Repositories/vidi-dashboard/node_modules/seneca/seneca.js:1447:21)
    at Seneca.event_loop_stats (/Users/matteo/Repositories/vidi-dashboard/node_modules/vidi-toolbag-influx/toolbag-influx.js:122:10)
    at /Users/matteo/Repositories/vidi-dashboard/node_modules/seneca/seneca.js:1134:22
    at act_param_check (/Users/matteo/Repositories/vidi-dashboard/node_modules/seneca/seneca.js:1478:17)
    at Object.execute_action [as fn] (/Users/matteo/Repositories/vidi-dashboard/node_modules/seneca/seneca.js:1078:7)
    at Immediate._onImmediate (/Users/matteo/Repositories/vidi-dashboard/node_modules/seneca/node_modules/gate-executor/gate-executor.js:135:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

### PR DESCRIPTION
**Pull request by mcdonnelldean**
Closes #126

### CODE REVIEW

File: server/vidi-monolith-collector.js [hunk 1]
```diff
@@ -23,16 +23,14 @@ module.exports = (opts, server, done) => {
   setInterval(function () {
     seneca.act({role: 'vidi', group: 'toolbag', stat: 'process'}, function (err, data) {
       if (err) console.log(err.stack || err)
```
Comment (floridemai) [inline server/vidi-monolith-collector.js]: @mcdonnelldean Don't we want to return if we have an error? `if (err) { console.log(err.stack || err); return; }`?

**Comment by floridemai** [comment]
I know my comment comes a little late, but i cannot see how this fixes anything... You had defensive code against `data` why adding `data.length`?

PS; did not cloned and try to run it yet...

**Comment by mcdonnelldean** [comment]
@floridemai This is all changed, this was just to get it over the hump, new branch coming shortly.
